### ISSUE TITLE
More thorough testing

### ISSUE THREAD

**Issue by apttx** [themed-styling/core#133]
# Add

* [x] negative numbers
* [x] function values
* [x] empty function calls
* [x] undefined values
* [x] values passed via prop

**Comment by hexagon6** [comment]
Maybe try to use a fuzzer? e.g. https://www.npmjs.com/package/test-each#fuzz-testing

**Comment by apttx** [comment]
Not sure how applicable this is to this, but I'll keep it in mind. Thanks!
